// Code generated by MockGen. DO NOT EDIT.
// Source: gateway.go

// Package mocks is a generated GoMock package.
package mocks

import (
	models "payment-gateway/internal/models"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockServiceGateway is a mock of ServiceGateway interface.
type MockServiceGateway struct {
	ctrl     *gomock.Controller
	recorder *MockServiceGatewayMockRecorder
}

// MockServiceGatewayMockRecorder is the mock recorder for MockServiceGateway.
type MockServiceGatewayMockRecorder struct {
	mock *MockServiceGateway
}

// NewMockServiceGateway creates a new mock instance.
func NewMockServiceGateway(ctrl *gomock.Controller) *MockServiceGateway {
	mock := &MockServiceGateway{ctrl: ctrl}
	mock.recorder = &MockServiceGatewayMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockServiceGateway) EXPECT() *MockServiceGatewayMockRecorder {
	return m.recorder
}

// Deposit mocks base method.
func (m *MockServiceGateway) Deposit(req models.Transaction) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Deposit", req)
	ret0, _ := ret[0].(error)
	return ret0
}

// Deposit indicates an expected call of Deposit.
func (mr *MockServiceGatewayMockRecorder) Deposit(req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Deposit", reflect.TypeOf((*MockServiceGateway)(nil).Deposit), req)
}

// GetGateway mocks base method.
func (m *MockServiceGateway) GetGateway(countryID int) (*models.Gateway, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGateway", countryID)
	ret0, _ := ret[0].(*models.Gateway)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGateway indicates an expected call of GetGateway.
func (mr *MockServiceGatewayMockRecorder) GetGateway(countryID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGateway", reflect.TypeOf((*MockServiceGateway)(nil).GetGateway), countryID)
}

// Withdrawal mocks base method.
func (m *MockServiceGateway) Withdrawal(req models.Transaction) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Withdrawal", req)
	ret0, _ := ret[0].(error)
	return ret0
}

// Withdrawal indicates an expected call of Withdrawal.
func (mr *MockServiceGatewayMockRecorder) Withdrawal(req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Withdrawal", reflect.TypeOf((*MockServiceGateway)(nil).Withdrawal), req)
}
